version: '3.8'  # Use an appropriate version for your Docker Compose setup

services:
  liability:
    build:
      context: ./liability
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Map container port 8080 to host port 8080

  axonserver:
    image: axoniq/axonserver:latest  # Use the appropriate Axon Server image
    ports:
      - "8024:8024"  # Management and HTTP API port
      - "8125:8125"  # Event store port
      - "8224:8224"  # Cluster server port
    